# Generated by Django 4.2 on 2023-05-03 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('datenaissence', models.DateField()),
                ('photo', models.ImageField(upload_to='etudiant/img/pdp/%y')),
                ('NiveauEtudiant', models.CharField(choices=[('1er annee', '1er annee'), ('2eme annee', '2eme annee'), ('3eme annee', '3eme annee'), ('4eme annee', '4eme annee'), ('5eme annee', '5eme annee'), ('6eme annee', '6eme annee')], max_length=50)),
                ('datecreation', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
