# Generated by Django 4.2 on 2023-05-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0007_alter_etudiant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='bio',
            field=models.TextField(blank=True, default='Etudiant On GoStudy E-learning', null=True),
        ),
    ]
