# Generated by Django 4.2 on 2023-05-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0009_alter_etudiant_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='NiveauEtudiant',
            field=models.CharField(blank=True, choices=[('1er annee', '1er annee'), ('2eme annee', '2eme annee'), ('3eme annee', '3eme annee'), ('4eme annee', '4eme annee'), ('5eme annee', '5eme annee'), ('6eme annee', '6eme annee')], max_length=50),
        ),
    ]
