# Generated by Django 4.2 on 2023-05-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0003_enrollement'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollement',
            name='datecreation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
