# Generated by Django 4.2 on 2023-05-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0005_rename_course_enrollement_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(default='etudiant/img/23/def.png', upload_to='etudiant/img/pdp/%y'),
        ),
    ]
