# Generated by Django 4.2 on 2023-05-18 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_cover_alter_course_duration_and_more'),
        ('etudiant', '0008_etudiant_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
