# Generated by Django 4.2 on 2023-05-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0010_alter_etudiant_niveauetudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='datenaissence',
            field=models.DateField(blank=True),
        ),
    ]
