# Generated by Django 4.2 on 2023-05-03 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_categorie_course_course_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='avis',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
