# Generated by Django 4.2 on 2023-05-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
