# Generated by Django 4.2 on 2023-05-03 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
        ('courses', '0005_course_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='eleve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etudiant.etudiant'),
        ),
    ]
