# Generated by Django 4.2 on 2023-05-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_enseignant_alter_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
