# Generated by Django 4.2 on 2023-05-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.categorie'),
        ),
    ]
