# Generated by Django 4.2 on 2023-05-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='beginner', max_length=90, null=True),
        ),
    ]
