# Generated by Django 4.2 on 2023-05-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.ImageField(default='', null=True, upload_to='CourseCovers/img/%y/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(default='', null=True, upload_to='CourseVideos/lecons/%y'),
        ),
    ]
