# Generated by Django 4.2 on 2023-05-07 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='avis',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
